[package]
name = "html-streaming-editor"
version = "0.1.0"
edition = "2021"
authors = [":kelko: <kelko@me.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"peg" = "0.8.0"
"tl" = "0.7.5"
snafu = { version = "0.7", features = ["backtraces"]}
clap = "3.2"
exitcode = "1.1.2"